import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Whiteflower Frames",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-25 bg-zinc-50 dark:bg-white">
          <Link href="/" className="p-4 text-2xl font-bold">
            Whiteflower Frames
          </Link>
          <Link
            href="/about"
            className="p-4 text-lg font-medium hover:underline"
          >
            About
          </Link>
          <Link
            href="/galleries"
            className="p-4 text-lg font-medium hover:underline"
          >
            Galleries
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
